//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class brands
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public brands()
        {
            this.products = new HashSet<products>();
        }
    
        public System.Guid braId { get; set; }
        public string braName { get; set; }
        public string braNameDP { get; set; }
        public string braCodeDP { get; set; }
        public string barDescriptionDP { get; set; }
        public string braDescription { get; set; }
        public string braCode { get; set; }
        public string braImage { get; set; }
        public bool braEdited { get; set; }
        public Nullable<int> braPercent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products> products { get; set; }
    }
}
