//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoriesDP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categoriesDP()
        {
            this.products = new HashSet<products>();
        }
    
        public System.Guid cdpId { get; set; }
        public string cdpNameDP { get; set; }
        public string cdpDescriptionDP { get; set; }
        public string cdpName { get; set; }
        public string cdpDescription { get; set; }
        public string cdpImage { get; set; }
        public Nullable<System.Guid> cdpParentId { get; set; }
        public bool cdpStatus { get; set; }
        public bool cdpEdited { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products> products { get; set; }
    }
}
