//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoriesDP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categoriesDP()
        {
            this.products = new HashSet<products>();
        }
    
        public System.Guid cdpId { get; set; }
        public string cdpNameDP { get; set; }
        public string cdpDescriptionDP { get; set; }
        public string cdpName { get; set; }
        public string cdpDescription { get; set; }
        public string cdpImage { get; set; }
        public Nullable<System.Guid> cdpParentId { get; set; }
        public bool cdpStatus { get; set; }
        public bool cdpEdited { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products> products { get; set; }
    }
}
