//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailUserPoints
    {
        public int Id { get; set; }
        public string IdUser { get; set; }
        public string UserFriendEmail { get; set; }
        public Nullable<System.DateTime> DayInvited { get; set; }
        public Nullable<bool> StatusofPromo { get; set; }
        public Nullable<int> PointsEarned { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
