//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public string idUser { get; set; }
        public Nullable<int> Payment { get; set; }
        public Nullable<int> DeliveryAddress { get; set; }
        public string PromoCode { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> DateS { get; set; }
        public Nullable<System.DateTime> EstimatedDate { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<bool> Delivered { get; set; }
    }
}
