//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public string idUser { get; set; }
        public Nullable<int> Payment { get; set; }
        public Nullable<int> DeliveryAddress { get; set; }
        public string PromoCode { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> DateS { get; set; }
        public Nullable<System.DateTime> EstimatedDate { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<bool> Delivered { get; set; }
    }
}
