//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class postnumre
    {
        public short postnummer { get; set; }
        public short poststedID { get; set; }
        public string kategoriID { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lon { get; set; }
    
        public virtual kategorier kategorier { get; set; }
        public virtual poststed poststed { get; set; }
    }
}
