//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoCodeUsed
    {
        public int id { get; set; }
        public string idUser { get; set; }
        public string PromoCode { get; set; }
        public Nullable<bool> Used { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> TotalPriceFinal { get; set; }
    
        public virtual PromotionCode PromotionCode { get; set; }
    }
}
