//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoCodeUsed
    {
        public string idUser { get; set; }
        public string PromoCode { get; set; }
        public Nullable<bool> Used { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> TotalPriceFinal { get; set; }
        public Nullable<System.DateTime> DateUsed { get; set; }
        public int id { get; set; }
    
        public virtual PromotionCode PromotionCode { get; set; }
    }
}
