//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int IdOrderDetail { get; set; }
        public string IdUser { get; set; }
        public string Products { get; set; }
        public decimal TotalPrice { get; set; }
        public string Paymentmethod { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> Orderstatus { get; set; }
        public Nullable<int> IdDelivery { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public string UsedPromo { get; set; }
        public string Comments { get; set; }
        public string Shoppingcarts { get; set; }
    
        public virtual DeliveryType DeliveryType { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
