//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int IdOrderDetail { get; set; }
        public string IdUser { get; set; }
        public string Products { get; set; }
        public decimal TotalPrice { get; set; }
        public string Paymentmethod { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> Orderstatus { get; set; }
        public Nullable<int> IdDelivery { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public string UsedPromo { get; set; }
        public string Comments { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual DeliveryType DeliveryType { get; set; }
    }
}
