//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public int Id { get; set; }
        public string IdUser { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string Latitude { get; set; }
        public string Length { get; set; }
        public string Image { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
